name: Foo
on:
  push:

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.KEY_PEM }}
      - name: a
        run: |
          ls .ssh/
          echo $KEY_PEM
        env:
          KEY_PEM: ${{ secrets.KEY_PEM }}
