name: Foo
on:
  push:

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.KEY_PEM }}
      - name: Add SSH Key
        env: 
          KEY: ${{ secrets.KEY_PEM }}
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "$KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          wc -l ~/.ssh/id_rsa
          echo ${KEY:12}
          ssh-keygen -lf ~/.ssh/id_rsa
